# -*- coding: utf-8 -*-
"""Generate Content with LLM

使用 LLM 生成站点内容：
1. 收集公司信息
2. 生成提示词
3. 让用户将提示词发送给 LLM
4. 保存 LLM 生成的内容

用法:
    python -m cli.generate_content
"""

import json
import sys
from pathlib import Path
from typing import Dict


def collect_company_info() -> Dict[str, str]:
    """收集公司基本信息"""
    print("=" * 60)
    print("  Docms 内容生成工具 - 使用 LLM 快速创建企业站点")
    print("=" * 60)
    print()
    print("请提供以下公司信息（将用于生成个性化内容）：")
    print()

    info = {}

    info["company_name"] = input("公司名称: ").strip()
    info["industry"] = input("所属行业（如: 智能水培设备、软件开发等）: ").strip()
    info["main_products"] = input("主要产品/服务（用逗号分隔）: ").strip()
    info["company_description"] = input("公司简介（一句话）: ").strip()
    info["target_customers"] = input("目标客户（如: 家庭用户、企业客户等）: ").strip()
    info["product_categories"] = input("产品分类（用逗号分隔，如: 家用设备、商用设备）: ").strip()
    info["post_categories"] = input("文章分类（用逗号分隔，如: 行业动态、技术文档）: ").strip()

    print()
    print("收集完成！")
    return info


def generate_database_prompt(info: Dict[str, str]) -> str:
    """生成数据库内容生成提示词"""
    prompt = f"""# 任务：为企业官网生成 SQLite 数据库填充脚本

## 公司信息
- 公司名称：{info['company_name']}
- 所属行业：{info['industry']}
- 主要产品/服务：{info['main_products']}
- 公司简介：{info['company_description']}
- 目标客户：{info['target_customers']}
- 产品分类：{info['product_categories']}
- 文章分类：{info['post_categories']}

## 要求

请生成一个完整的 SQL 脚本（seed_data.sql），用于填充以下数据库表：

### 1. site_setting（站点配置）
插入以下配置项：
- site_name: {info['company_name']}
- site_description: {info['company_description']}
- phone: 生成一个合理的电话号码
- email: 生成一个合理的邮箱
- address: 生成一个合理的地址
- about_us: 生成一段 200 字左右的公司介绍

### 2. site_column（栏目）
创建以下栏目：
- 首页（slug: home, type: CUSTOM）
- 产品中心（slug: products, type: PRODUCT）
- 新闻资讯（slug: news, type: POST）
- 关于我们（slug: about, type: SINGLE_PAGE）
- 联系我们（slug: contact, type: SINGLE_PAGE）

### 3. single_page（单页内容）
为"关于我们"和"联系我们"栏目生成内容（HTML格式）

### 4. product_category（产品分类）
根据 "{info['product_categories']}" 创建 3-5 个产品分类

### 5. product（产品）
创建 8-12 个产品，要求：
- 名称要符合 {info['industry']} 行业特点
- 每个产品包含：name, slug, summary（50字）, description_html（200字HTML）
- 价格范围合理
- 至少 3 个产品设置为推荐（is_recommended=1）
- 状态都设为 online
- 每个产品关联至少一个分类

### 6. post_category（文章分类）
根据 "{info['post_categories']}" 创建 3-5 个文章分类

### 7. post（文章）
创建 6-10 篇文章，要求：
- 标题与 {info['industry']} 相关
- 每篇文章包含：title, slug, summary（100字）, content_html（300-500字HTML）
- 至少 3 篇设置为推荐（is_recommended=1）
- 状态都设为 published
- 每篇文章关联至少一个分类

## 输出格式

生成一个可直接执行的 SQL 脚本，包含所有 INSERT 语句。

SQL 脚本开头添加：
```sql
-- Generated by Docms Content Generator
-- Company: {info['company_name']}
-- Date: {{{{ current_date }}}}

-- 清空现有数据（可选）
DELETE FROM product_category_link;
DELETE FROM post_category_link;
DELETE FROM product;
DELETE FROM post;
DELETE FROM product_category;
DELETE FROM post_category;
DELETE FROM single_page;
DELETE FROM site_column;
DELETE FROM site_setting;
```

请确保：
1. 所有内容真实、合理、专业
2. HTML 内容格式正确，使用 <p>, <h2>, <ul> 等标签
3. slug 使用小写字母和连字符
4. 外键关联正确
5. 不要使用 Lorem Ipsum 占位文本

开始生成 SQL 脚本：
"""
    return prompt


def generate_template_prompt(info: Dict[str, str]) -> str:
    """生成模板生成提示词"""
    prompt = f"""# 任务：为企业官网生成 Jinja2 模板文件

## 公司信息
- 公司名称：{info['company_name']}
- 所属行业：{info['industry']}
- 公司简介：{info['company_description']}

## 要求

请生成以下 Jinja2 模板文件，风格要符合 {info['industry']} 行业特点：

### 1. home.html（首页）
- 继承 base.html
- 包含 hero 区域，展示公司 slogan
- 展示推荐产品（使用 featured_products 变量）
- 展示最新文章（使用 featured_posts 变量）
- 风格：现代、专业、简洁

### 2. product_list.html（产品列表页）
- 继承 base.html
- 左侧：产品分类导航（使用 categories 变量）
- 右侧：产品网格布局（使用 products 变量）
- 每个产品卡片显示：图片、名称、简介、价格、查看详情按钮

### 3. product_detail.html（产品详情页）
- 继承 base.html
- 左侧：产品图片
- 右侧：产品信息（名称、价格、简介）
- 下方：产品详细描述（HTML）
- 相关产品推荐（使用 related_products 变量）

### 4. post_list.html（文章列表页）
- 继承 base.html
- 文章列表（使用 posts 变量）
- 侧边栏：分类导航、热门文章

### 5. post_detail.html（文章详情页）
- 继承 base.html
- 文章标题、发布日期、内容
- 相关文章推荐

### 6. about.html（关于我们）
- 继承 base.html
- 展示公司介绍、团队、发展历程

### 7. contact.html（联系我们）
- 继承 base.html
- 联系表单（姓名、邮箱、电话、主题、留言）
- 联系方式展示（电话、邮箱、地址）

## 技术要求
- 使用 Tailwind CSS 类名（已在 base.html 中引入）
- 响应式设计
- 现代化的 UI 风格
- 颜色主题：根据 {info['industry']} 行业选择合适的主色调

## 输出格式
为每个模板文件生成完整的 HTML 代码，包含文件名注释。

开始生成模板：
"""
    return prompt


def save_prompt_to_file(prompt: str, filename: str):
    """保存提示词到文件"""
    prompt_dir = Path("prompts")
    prompt_dir.mkdir(exist_ok=True)

    file_path = prompt_dir / filename
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(prompt)

    print(f"  ✓ 提示词已保存到: {file_path}")


def save_generated_content(content_type: str):
    """保存 LLM 生成的内容"""
    print()
    print("=" * 60)
    print(f"  保存 {content_type} 内容")
    print("=" * 60)
    print()
    print("请将 LLM 生成的内容粘贴到下方（输入 '###END###' 结束）：")
    print()

    lines = []
    while True:
        try:
            line = input()
            if line.strip() == "###END###":
                break
            lines.append(line)
        except EOFError:
            break

    content = "\n".join(lines)

    if content_type == "数据库脚本":
        file_path = Path("seed_data.sql")
    elif content_type == "模板文件":
        # 询问文件名
        filename = input("请输入文件名（如 home.html）: ").strip()
        file_path = Path("templates") / filename
        file_path.parent.mkdir(parents=True, exist_ok=True)
    else:
        return

    with open(file_path, "w", encoding="utf-8") as f:
        f.write(content)

    print()
    print(f"✓ 内容已保存到: {file_path}")


def main():
    """主流程"""
    # 检查是否在站点目录中
    if not Path("site.yaml").exists():
        print("❌ 错误: 请在站点目录中运行此命令")
        print("提示: 先使用 'python -m cli.create_site' 创建站点")
        sys.exit(1)

    print()
    print("🤖 Docms 智能内容生成器")
    print()
    print("此工具将帮助你使用 LLM 生成以下内容：")
    print("  1. 数据库填充脚本（产品、文章等）")
    print("  2. 页面模板文件（HTML）")
    print()
    print("工作流程：")
    print("  → 收集公司信息")
    print("  → 生成 LLM 提示词")
    print("  → 将提示词发送给 LLM（如 Claude、GPT-4）")
    print("  → 保存 LLM 返回的内容")
    print()

    # 收集公司信息
    info = collect_company_info()

    print()
    print("=" * 60)
    print("  生成提示词")
    print("=" * 60)

    # 生成数据库提示词
    print()
    print("📝 生成数据库内容提示词...")
    db_prompt = generate_database_prompt(info)
    save_prompt_to_file(db_prompt, "database_prompt.txt")

    # 生成模板提示词
    print()
    print("📝 生成模板内容提示词...")
    template_prompt = generate_template_prompt(info)
    save_prompt_to_file(template_prompt, "template_prompt.txt")

    print()
    print("=" * 60)
    print("  下一步")
    print("=" * 60)
    print()
    print("提示词已生成！请按以下步骤操作：")
    print()
    print("1. 打开 prompts/database_prompt.txt")
    print("2. 将内容复制并发送给 LLM（如 Claude、GPT-4）")
    print("3. 将 LLM 返回的 SQL 脚本保存为 seed_data.sql")
    print()
    print("4. 打开 prompts/template_prompt.txt")
    print("5. 将内容复制并发送给 LLM")
    print("6. 将 LLM 返回的每个模板保存到 templates/ 目录")
    print()
    print("7. 初始化数据库：")
    print("   alembic upgrade head")
    print("   sqlite3 instance/database.db < seed_data.sql")
    print()
    print("8. 启动服务器：")
    print("   python app.py")
    print()
    print("💡 提示：你也可以使用此工具的交互式保存功能")

    # 询问是否立即保存内容
    print()
    choice = input("是否现在保存 LLM 生成的内容？(y/n): ").strip().lower()

    if choice == "y":
        while True:
            print()
            print("选择要保存的内容类型：")
            print("  1. 数据库脚本")
            print("  2. 模板文件")
            print("  3. 退出")
            print()
            choice = input("请选择 (1-3): ").strip()

            if choice == "1":
                save_generated_content("数据库脚本")
            elif choice == "2":
                save_generated_content("模板文件")
            elif choice == "3":
                break

    print()
    print("✅ 完成！祝你使用愉快！")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n❌ 用户取消操作")
        sys.exit(1)
    except Exception as e:
        print(f"\n❌ 错误: {e}")
        sys.exit(1)
